name: CI

on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+

env:
  IMAGE_NAME: ${{ secrets.DOCKER_LOGIN }}/tcommerce-web-client

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log into Docker registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - name: Build images (multistage)
      run: |
        docker pull ${IMAGE_NAME}:builder
        docker pull ${IMAGE_NAME}:latest

        docker build \
          --target builder \
          --cache-from ${IMAGE_NAME}:builder \
          -t ${IMAGE_NAME}:builder \
          .
        docker build \
          --cache-from ${IMAGE_NAME}:latest \
          --cache-from ${IMAGE_NAME}:builder \
          -t ${IMAGE_NAME}:latest \
          .
    - name: Push images
      run: |
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        docker push ${IMAGE_NAME}:builder
        docker push ${IMAGE_NAME}:latest

        docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${VERSION}
        docker push ${IMAGE_NAME}:${VERSION}

  deploy:
    needs: build-push

    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          passphrase: ${{ secrets.SERVER_SSH_PRIVATE_KEY_PASSPHRASE }}
          script: |
            manage-docker pull-restart client prod
